### ISSUE TITLE
HelloFX not starting

### ISSUE THREAD

**Issue by DieterHolz** [gluonhq/client-gradle-plugin#39] opened 2019-08-07 11:08 UTC
running the sample 'HelloFX' leads to this error

`> Task :run FAILED
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: /Users/dieter/.openjfx/cache/12.0.2/libprism_es2.dylib: dlopen(/Users/dieter/.openjfx/cache/12.0.2/libprism_es2.dylib, 1): no suitable image found.  Did find:
        /Users/dieter/.openjfx/cache/12.0.2/libprism_es2.dylib: code signature in (/Users/dieter/.openjfx/cache/12.0.2/libprism_es2.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
        /Users/dieter/.openjfx/cache/12.0.2/libprism_es2.dylib: stat() failed with errno=38
j`

What can I do?

**Comment by jperedadnr** [comment] 2019-08-07 12:06
Maybe you can try to remove the cache at `/Users/dieter/.openjfx`?

**Comment by DieterHolz** [comment] 2019-08-07 12:15
I did that already. Doesn't help.

BTW: I'm using AdoptOpenJDK 11.0.4

**Comment by jperedadnr** [comment] 2019-08-07 21:07
I've found an unrelated issue but with similar error messages [here](https://github.com/ycm-core/YouCompleteMe/issues/3158). It mentions the Mac's System Integrity Protection. While it should only affect a given number of system folders, is there any chance that you have extended it to your `Users` folder? Do you have any kind of writing restrictions applied?

There is an option to move this cache to a different location, using `System.setProperty("javafx.cachedir", "path/to/cache");` in your main method of the Application class (right before `launch()`).

Can you try setting a writable folder?

**Comment by DieterHolz** [comment] 2019-08-08 09:23
`csrutil disable` helps. HelloFX can be started via `gradlew run`.

I never did anything with SIP before and I don't think I'm the only one with this problem.

Shouldn't it be fixed in OpenJFX?

**Comment by johanvos** [comment] 2019-08-08 09:29
Can you open an issue for this on https://github.com/javafxports/openjfx ?

**Comment by taubeklavs** [comment] 2019-08-09 14:22
I had the same issue, it was related to https://github.com/AdoptOpenJDK/openjdk-build/issues/1211

Reverting `openjdk` version to `jdk-11.0.3+7` fixes it.

**Comment by jperedadnr** [comment] 2019-08-20 09:40
The issue is indeed related to AdoptOpenJDK, and it seems it has been already fixed. The latest [prerelease](https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk11u-2019-08-19-00-56/OpenJDK11U-jdk_x64_mac_hotspot_2019-08-19-00-56.tar.gz) works fine for me.

@DieterHolz if you can verify this, feel free to close this issue.

**Closed** 2019-09-05 07:03 UTC
