### ISSUE TITLE
nativeCompile fails with too long command line on Windows

### ISSUE THREAD

**Issue by AstralStorm** [gluonhq/client-gradle-plugin#74] opened 2020-05-12 12:39 UTC
When there's a lot of jar files in the path, the nativeCompile task fails on Windows with log file containing:

```
Output
======
The command line is too long.
```

This is because all the jars are listed in the classpath given to native-image.cmd and Windows command prompt is very limiting.
A recommended fix would be to use a parameter file, with @some-temp-file-path argument.

**Comment by tiainen** [comment] 2020-05-18 12:36
Duplicate of https://github.com/gluonhq/substrate/issues/597

**Closed by tiainen** 2020-05-18 12:36 UTC
